# ==============================================================================
# 02_nestedness.R
#
# Contribution-to-nestedness scores (cs) following Hosseinioun et al. (2025)
#
# For each skill s, cs quantifies how much the skill's occupational presence
# pattern reinforces (+) or disrupts (-) the overall nested structure of the
# skill-occupation matrix:
#
#   cs_s = (N_obs - mean(N*_s)) / sd(N*_s)
#
# where N_obs is the NODF of the empirically observed matrix and {N*_s} is a
# null ensemble generated by randomising skill s across occupations while
# holding its generality (column sum) constant (5,000 iterations per skill,
# following Hosseinioun et al. 2025, Methods).
#
# A positive cs indicates that skill s's presence pattern reinforces the
# overall hierarchical nesting; a negative cs indicates misalignment.
# This binary split (nested: cs > 0 / un-nested: cs < 0) is used to describe
# the structural position of each skill.
#
# The archetype typology used in estimation (SC_Scaffolding, SC_Specialized,
# Physical_Terminal) is derived *downstream* in the modelling scripts from the
# continuous cs values produced here.
#
# Inputs:
#   dt   loaded via R/00_setup_comun.R  (source occupations + skill_name columns)
#
# Outputs:
#   data/derived/skill_cs_scores.rds     skill-level cs table (skill_name, cs, nested)
#   data/derived/dt_con_cs_nestedness.rds  full 17.3M-row dataset with cs merged in
# ==============================================================================

# ------------------------------------------------------------------------------
# 0. Setup
# ------------------------------------------------------------------------------
gc()
source("R/00_setup_comun.R")   # loads dt; sets output_dir

library(vegan)          # nestednodf()
library(data.table)

derived_dir <- "data/derived"
dir.create(derived_dir, showWarnings = FALSE, recursive = TRUE)

N_SIM <- 5000L   # null-model iterations per skill (Hosseinioun et al. 2025)
SEED  <- 42L

# ==============================================================================
# 1. Build binary skill-occupation matrix (2015 baseline)
#
# Source occupations in dt are exactly those with RCA > 1 at t0 for each skill.
# Taking unique (source, skill_name) pairs therefore recovers the 2015
# specialisation matrix without reloading the raw O*NET files.
# ==============================================================================
message("\n>>> Step 1: Building binary skill-occupation matrix (2015 baseline)...")

occ_skill <- unique(dt[, .(soc = source, skill = skill_name)])

# Wide binary matrix: rows = occupations, columns = skills
M_wide  <- dcast(occ_skill, soc ~ skill, fun.aggregate = length, fill = 0L)
occ_ids <- M_wide$soc
M       <- as.matrix(M_wide[, -1, with = FALSE])
rownames(M) <- occ_ids

# Pre-sort by marginal totals (required for NODF; avoids repeated re-sorting
# inside nestednodf() calls, which is the main speed bottleneck)
M <- M[order(rowSums(M), decreasing = TRUE),
       order(colSums(M), decreasing = TRUE)]

skill_names <- colnames(M)
n_skills    <- length(skill_names)
n_occs      <- nrow(M)

message(sprintf("  Matrix: %d occupations x %d skills", n_occs, n_skills))

# ==============================================================================
# 2. Observed nestedness
# ==============================================================================
message("\n>>> Step 2: Computing observed NODF...")

N_obs <- nestednodf(M, order = FALSE, weighted = FALSE)$statistic[["NODF"]]
message(sprintf("  Observed NODF: %.4f", N_obs))

# ==============================================================================
# 3. Contribution scores (cs) via column-permutation null model
#
# For each skill s:
#   - Shuffle its column (keeps generality = column sum constant)
#   - Recompute NODF without re-sorting (matrix already sorted)
#   - cs_s = (N_obs - mean(null)) / sd(null)
#
# Sequential loop with progress bar.  For 161 skills x 5000 sims this takes
# ~30–60 min on a single core; set N_SIM <- 500 for faster development runs.
# ==============================================================================
message(sprintf(
  "\n>>> Step 3: Computing cs for %d skills (%d simulations each)...",
  n_skills, N_SIM
))
message("  (Estimated runtime: ~40 min at N_SIM = 5000; set N_SIM = 500 for dev)")

set.seed(SEED)
cs_vec <- numeric(n_skills)

for (i in seq_len(n_skills)) {

  if (i %% 20 == 0 || i == 1)
    message(sprintf("  skill %d / %d : %s", i, n_skills, skill_names[i]))

  focal_col <- M[, i]

  # Null distribution: shuffle column i, recompute NODF
  null_N <- replicate(N_SIM, {
    M_null      <- M
    M_null[, i] <- sample(focal_col)
    nestednodf(M_null, order = FALSE, weighted = FALSE)$statistic[["NODF"]]
  })

  mu  <- mean(null_N)
  sig <- sd(null_N)

  cs_vec[i] <- if (sig > 0) (N_obs - mu) / sig else NA_real_
}

# ==============================================================================
# 4. Assemble skill-level table
# ==============================================================================
message("\n>>> Step 4: Assembling results...")

skill_stats <- data.table(
  skill_name = skill_names,
  cs         = cs_vec
)

# Binary classification following Hosseinioun et al. (2025):
# nested = cs > 0 (skill's presence reinforces overall hierarchy)
# un-nested = cs <= 0 (skill's presence diminishes hierarchy)
skill_stats[, nested := fifelse(cs > 0, "nested", "un-nested")]

message(sprintf(
  "  Nested (cs > 0):    %d skills (%.1f%%)",
  sum(skill_stats$nested == "nested", na.rm = TRUE),
  mean(skill_stats$nested == "nested", na.rm = TRUE) * 100
))
message(sprintf(
  "  Un-nested (cs <= 0): %d skills (%.1f%%)",
  sum(skill_stats$nested == "un-nested", na.rm = TRUE),
  mean(skill_stats$nested == "un-nested", na.rm = TRUE) * 100
))
message(sprintf(
  "  cs range: [%.3f, %.3f]  median: %.3f",
  min(skill_stats$cs, na.rm = TRUE),
  max(skill_stats$cs, na.rm = TRUE),
  median(skill_stats$cs, na.rm = TRUE)
))

# ==============================================================================
# 5. Save skill-level table
# ==============================================================================
saveRDS(skill_stats, file.path(derived_dir, "skill_cs_scores.rds"))
message("\n  Saved: data/derived/skill_cs_scores.rds")

# ==============================================================================
# 6. Merge cs into dt and save the enriched triadic dataset
#
# Note: only cs and nested are merged here.  The downstream typology
# (SC_Scaffolding / SC_Specialized / Physical_Terminal) is constructed in the
# estimation scripts (03_structural_models.R, 04_structural_models_nestedness.R)
# from the continuous cs column, so that its definition lives alongside the
# models that use it.
# ==============================================================================
message("\n>>> Step 5: Merging cs into dt...")

dt <- merge(dt, skill_stats[, .(skill_name, cs, nested)],
            by = "skill_name", all.x = TRUE)

n_missing <- sum(is.na(dt$cs))
if (n_missing > 0)
  warning(sprintf(
    "%d rows in dt have no cs value (%.2f%% of total).",
    n_missing, n_missing / nrow(dt) * 100
  ))

out_path <- file.path(derived_dir, "dt_con_cs_nestedness.rds")
saveRDS(dt, out_path)
message(sprintf("  Saved: %s  (%s rows)", out_path,
                format(nrow(dt), big.mark = ",")))

rm(M, M_wide, M_null, occ_skill); gc()
message("\n>>> Nestedness computation complete.")